#!/usr/bin/env python3
"""Silicide-sink check (paper item: is tau_eff <= 5e-14 s realisable?).
The lifetime-killed island (tau0 = 1 ps) is replaced by a metal core through the whole Si film
(ohmic electrode = infinite recombination), wrapped by n+ shells so the metal never touches the p bodies.
The island Si keeps the normal lifetime. The metal core is the tap electrode (-> Rtap in the circuit);
the n+ neck through the BOX is removed. Source decks: 1007_ddsplit/DDS_{BASE,TE8_XS60}.in."""
import os, re
SRC = '/home/ysseo/novel/1007_ddsplit'
CASES = [  # name, source deck, n+ shell (um), kill island lifetime?, sink?
    ('SINK_TE8_XS60',    'DDS_TE8_XS60', 0.010, False, True),
    ('SINK5_TE8_XS60',   'DDS_TE8_XS60', 0.005, False, True),
    ('SINK_BASE',        'DDS_BASE',     0.010, False, True),
    ('NOKILL_TE8_XS60',  'DDS_TE8_XS60', None,  False, False),   # control: island with normal lifetime, bottom tap
]
for name, src, shell, kill, sink in CASES:
    s = open(os.path.join(SRC, src + '.in')).read()
    s = re.sub(r'\b%s\b' % src, name, s)
    s = s.replace(src + '_', name + '_')
    hdr = (f'# {name} : from {src}. ' + (f'Island = metal core (tap electrode, Si-film deep) + n+ shells {shell*1000:.0f} nm, '
           'island Si lifetime NOT killed, neck removed.' if sink else 'Island lifetime NOT killed (control), tap at the bottom of the n+ neck.')
           + ' Generated by 1010_sink/make_sink.py\n')
    s = hdr + s
    s = s.replace('material region=10 taun0=1e-12 taup0=1e-12\n', '').replace('material region=9 taun0=1e-12 taup0=1e-12\n', '')
    if sink:
        s = s.replace('region num=9 x.min=$XiL x.max=$XiR y.min=$tsi y.max=$Ybot silicon\n', '')
        s = s.replace('doping uniform conc=1e20 n.type reg=9\n', '')
        s = s.replace('electrode name=tap x.min=$XiL x.max=$XiR y.min=$Ybot y.max=$Ybot',
                      f'set XcL = $XiL+{shell}\nset XcR = $XiR-{shell}\n'
                      'electrode name=tap x.min=$XcL x.max=$XcR y.min=0 y.max=$tsi')
        s = s.replace('x.mesh loc=$XiR spac=0.003\n', f'x.mesh loc=$XiL+{shell} spac=0.001\nx.mesh loc=$XiR-{shell} spac=0.001\nx.mesh loc=$XiR spac=0.003\n')
        s = s.replace('probe name=V_neck   potential x=0.65 y=0.15\n', '')
        assert 'region num=9' not in s and 'XcL' in s, name
    open(name + '.in', 'w').write(s); print('wrote', name + '.in')
