#!/usr/bin/env python3
"""Triristor calibration decks (paper item 1): reproduce the measured double latch of
Noh et al., IEEE EDL 46(8) 2025 (bulk n-MOSFET, L_G 3 um, floating body) with our model set.
Doping from the paper's process flow and SIMS (Fig. 1e):
  p-well  : Gaussian, peak 5e16 at 0.10 um, char 0.19 um  (SIMS: ~5e16 to 150 nm, ~2e16 at 300 nm)
  S/D As  : Gaussian, 7e20 at surface, char 0.055 um       (SIMS: 1e19 at ~100 nm, 1e17 at ~160 nm)
  background p: NBG (wafer, not given; SIMS floor < 1e16)
Body is floating (no substrate contact), as in the measurement. Drain: transient ramp 0 -> VMAX -> 0 V at RATE V/ms.
Targets: calib_targets.dat."""
import os
BASE = dict(VG=0.40, NBG=1e15, DSUB=5.0, TAU=1e-7, AUG=0, AN=1.0, BN=1.0, VMAX=13.0, RATE=0.7, IDVG=0)
CASES = [
    ('TRI_IDVG',            dict(IDVG=1)),
    ('TRI_DEF_VG0p40',      dict()),
    ('TRI_DEF_VG0p30',      dict(VG=0.30)),
    ('TRI_DEF_VG0p40_NBG1e16', dict(NBG=1e16)),
    ('TRI_DEF_VG0p40_D10',  dict(DSUB=10.0)),
    ('TRI_DEF_VG0p40_TAU1e-5', dict(TAU=1e-5)),
]
# ATLAS Selberherr defaults (electrons/holes, low-field branch); AN/BN scale them.
SELB = dict(an1=7.03e5, an2=7.03e5, bn1=1.231e6, bn2=1.231e6, ap1=6.71e5, ap2=1.582e6, bp1=1.693e6, bp2=2.036e6)

def deck(name, p):
    tr = (p['VMAX'] / p['RATE']) * 1e-3
    imp = 'impact selb length.rel'
    if p['AN'] != 1.0 or p['BN'] != 1.0:
        imp += ' an1=%.4g an2=%.4g bn1=%.4g bn2=%.4g ap1=%.4g ap2=%.4g bp1=%.4g bp2=%.4g' % (
            SELB['an1']*p['AN'], SELB['an2']*p['AN'], SELB['bn1']*p['BN'], SELB['bn2']*p['BN'],
            SELB['ap1']*p['AN'], SELB['ap2']*p['AN'], SELB['bp1']*p['BN'], SELB['bp2']*p['BN'])
    models = 'models print bgn consrh %sconmob fldmob fermi trap.tunnel bbt.std temp=300' % ('auger ' if p['AUG'] else '')
    L = [f'# {name} : triristor calibration deck. Params: ' + ', '.join(f'{k}={v}' for k, v in p.items()),
         '# Generated by 1010_calib/make_tri.py. Target device: Noh et al., IEEE EDL 46(8) 1269-1272, 2025.',
         'go atlas simflags="-P 1"',
         'set Lg = 3.0', 'set Lsd = 1.0', 'set tox = 0.02', 'set tgate = 0.25', f'set Dsub = {p["DSUB"]}',
         'mesh space.mult = 1.0 width = 600',
         'x.mesh loc=0.00 spac=0.25', 'x.mesh loc=$Lsd-0.25 spac=0.05', 'x.mesh loc=$Lsd spac=0.01', 'x.mesh loc=$Lsd+0.3 spac=0.05',
         'x.mesh loc=$Lsd+$Lg/2 spac=0.25', 'x.mesh loc=$Lsd+$Lg-0.4 spac=0.04', 'x.mesh loc=$Lsd+$Lg-0.1 spac=0.008', 'x.mesh loc=$Lsd+$Lg spac=0.005',
         'x.mesh loc=$Lsd+$Lg+0.15 spac=0.02', 'x.mesh loc=$Lsd+$Lg+$Lsd spac=0.25',
         'y.mesh loc=-$tox-$tgate spac=0.1', 'y.mesh loc=-$tox spac=0.005', 'y.mesh loc=0.00 spac=0.002', 'y.mesh loc=0.03 spac=0.008',
         'y.mesh loc=0.2 spac=0.02', 'y.mesh loc=0.45 spac=0.05', 'y.mesh loc=1.0 spac=0.2', 'y.mesh loc=$Dsub spac=0.8',
         'region num=1 x.min=$Lsd x.max=$Lsd+$Lg y.max=-$tox poly',
         'region num=2 x.min=$Lsd x.max=$Lsd+$Lg y.max=0 y.min=-$tox oxide',
         'region num=3 y.min=0 y.max=$Dsub silicon',
         'region num=4 x.max=$Lsd y.max=0 material=vacuum',
         'region num=5 x.min=$Lsd+$Lg y.max=0 material=vacuum',
         'electrode name=gate x.min=$Lsd x.max=$Lsd+$Lg y.min=-$tox-$tgate y.max=-$tox-$tgate',
         'electrode name=source x.max=$Lsd-0.1 y.min=0 y.max=0',
         'electrode name=drain x.min=$Lsd+$Lg+0.1 y.min=0 y.max=0',
         f'doping uniform conc={p["NBG"]:.3g} p.type reg=3',
         'doping gaussian conc=5e16 p.type peak=0.10 char=0.19 reg=3',
         'doping gaussian conc=7e20 n.type peak=0 char=0.055 x.right=$Lsd lat.char=0.04 reg=3',
         'doping gaussian conc=7e20 n.type peak=0 char=0.055 x.left=$Lsd+$Lg lat.char=0.04 reg=3',
         'doping uniform conc=1e21 n.type reg=1',
         f'save outf={name}_INIT.str',
         'contact name=gate n.poly',
         'probe name=VB_well potential x=$Lsd+$Lg/2 y=0.12',
         'probe name=VB_deep potential x=$Lsd+$Lg/2 y=1.0',
         'probe name=PH_well P.CONC x=$Lsd+$Lg/2 y=0.12',
         f'material material=silicon taun0={p["TAU"]:.3g} taup0={p["TAU"]:.3g}',
         models, imp,
         'output band.param con.band val.band recomb u.srh u.bbt impact e.field',
         'method newton climit=100 itlimit=200 trap maxtraps=10',
         'solve init', 'solve prev']
    if p['IDVG']:
        L += ['solve vdrain=0.05', f'log outf={name}_vd0p05.log',
              'solve vgate=0 vstep=-0.1 vfinal=-1.0 name=gate', 'log off', 'solve vgate=-1.0',
              f'log outf={name}_vd0p05_up.log', 'solve vgate=-1.0 vstep=0.05 vfinal=3.0 name=gate', 'log off',
              'solve vgate=-1.0', 'solve vdrain=1.0 vstep=0.1 vfinal=1.0 name=drain'.replace('vdrain=1.0 ', ''),
              f'log outf={name}_vd1_up.log', 'solve vgate=-1.0 vstep=0.05 vfinal=3.0 name=gate', 'log off', 'quit']
        return '\n'.join(L) + '\n'
    L += [f'solve vgate=0 vstep=0.05 vfinal={p["VG"]} name=gate',
          f'save outf={name}_VG.str master', f'log outf={name}.log j.electron j.hole']
    up = [x for x in (2, 4, 6, 7, 8, 9, 10, 11, 12) if x < p['VMAX']] + [p['VMAX']]
    dn = [x for x in (12, 11, 10, 9, 8, 7, 6, 4, 2, 0) if x < p['VMAX']]
    t, v0 = 0.0, 0.0
    for v, tag in [(x, 'UP') for x in up] + [(x, 'DN') for x in dn]:
        dt = abs(v - v0) / p['RATE'] * 1e-3; t += dt
        L += [f'solve vdrain={v} ramptime={dt:.6e} tstop={t:.6e} tstep=1e-9',
              f'save outf={name}_{tag}_{str(v).replace(".", "p")}.str']
        v0 = v
    L += ['log off', 'quit']
    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    for name, ch in CASES:
        p = dict(BASE); p.update(ch)
        if not os.path.exists(name + '.in'):
            open(name + '.in', 'w').write(deck(name, p)); print('wrote', name)
